import Head from 'next/head';
import Navigation from '../components/Navigation';

const About = () => {

    return (

        <>

            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-red h-screen w-full bg-[#ffffff] flex flex-col items-center justify-center space-y-10'>

                <Navigation/>

                <p className='text-center'>Some information about the
                    <br /><span className='uppercase'>EXCUSING 3000</span></p>

                <p className='w-[20vw]'>
                    EXCUSING 3000 is a tool that can be useful during extremely sticky situations.
                    <br/><br/>
                    Based on the situation you provide, 
                    the tool is able to return to you one of the most sophisticated excuses 
                    that you'll be able to furnish to the other subject.
                    <br/><br/>
                    This tool use's GPT-3 in order to generate your excuse. 
                    It is provided with the text-davinci-003 model which can perform any task in high-quality
                    and has an awesome instruction following.
                </p>

            </main>

        </>

    );

};

export default About;