import Head from 'next/head';
import { useState } from 'react';
import Navigation from '../components/Navigation';

const Home = () => {

	const [response, setResponse] = useState();
	const [value, setValue] = useState('');

	const onClick = async () => {

		console.log('click');

		const data = {
			query: value
		};

		const openai = await fetch('/api/openai', {
			method: 'POST',
			body: JSON.stringify(data),
		});

		const res = await openai.json();
		setResponse(JSON.stringify(res.answer).replace(/["?\]']+/g, ''));

	};

	return (

		<>

			<Head>
				<title></title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='bg-red h-screen w-full bg-[#ffffff] flex flex-col items-center justify-center space-y-10'>
				
				<Navigation/>
				
				<p className='text-center'>This is the first prototype of the
				<br/><span className='uppercase'>EXCUSING 3000</span></p>

				<div className='w-[20vw]'>
					<p className='mb-1'>Describe your situation at best</p>
					<textarea onChange={(e) => setValue(e.target.value)} value={value}  className='h-[12vh] w-[20vw] border-[1px] border-black resize-none outline-none overflow-hidden px-2 py-2' rows={4} maxLength={100}>
					
					</textarea>
					<div onClick={onClick} className='bg-black h-10 w-[20vw] mt-2 text-white flex items-center justify-center cursor-pointer'>
						Generate
					</div>
				</div>

				<div className='w-[20vw]'>
					{response}
				</div>

			</main>

		</>

	);

};

export default Home;